import type { Metadata } from "next";
import "./globals.css";
import { App, ConfigProvider } from "antd";
import "@ant-design/v5-patch-for-react-19";
import zhCN from "antd/locale/zh_CN";

import "dayjs/locale/zh-cn";
import dayjs from "dayjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  dayjs.locale("zh-cn");
  return (
    <html lang="zh">
      <body>
        <ConfigProvider locale={zhCN}>
          <App>{children}</App>
        </ConfigProvider>
      </body>
    </html>
  );
}
